server:
  port: 8888
  servlet:
    context-path: /zuul-demo

spring:
  application:
    name: zuul-demo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka-server/eureka 
    
zuul:
  routes:
    baidu:
      path: /baidu/**
      url: http://www.baidu1.com/
    csdn:
      path: /csdn/**
      url: https://www.csdn.net/
    eurekaServer:
      path: /eurekaServer/**
      url: http://localhost:8761/eureka-server/
    eurekaClient1:
      path: /eureka-client/**
      service-id: eureka-client
      strip-prefix: false        # http://localhost:8888/micro-gateway/eureka-client/say
    eurekaClient2:
      path: /ec/**
      service-id: eureka-client   # http://localhost:8888/micro-gateway/ec/eureka-client/say

      
