server:
  port: 8080
  servlet:
    context-path: /zookeeper-demo

admin:
  fileLocation: /Users/cj/space/java/admin-uploads
  
zk:
  server: 127.0.0.1:2181
  namespace: demo
  
user:
  fileLocation: /Users/cj/space/java/user-downloads
  fileServer: http://localhost:8080/zookeeper-demo/admin/images
  

#spring:
#  output:
#    ansi:
#      enabled: ALWAYS
#
#logging: 
#  level:
#    root: error
#    org.apache.curator: error
#    org.apache.zookeeper.ZooKeeper: error
#    org.apache.zookeeper.ClientCnxn: error