server:
  port: 8761
  servlet:
    context-path: /eureka-server

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
  client:
    registerWithEureka: false   # 是否向服务注册中心注册自己
    fetchRegistry: false        # 是否检索服务
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka-server/eureka}